import type { FlowDefinition } from "../types.js"

export const openaiCommandCodeRouter = {
  id: "openai-commandcode-router",
  title: "OpenAI + Command Code Router",
  summary: "Uses a subscription-backed orchestrator and low-cost workers, escalating difficult work back to the baseline model.",
  defaultAgent: "orchestrator",
  baselineAgent: "orchestrator",
  agents: {
    orchestrator: {
      description: "Routes work between ChatGPT and low-cost Command Code models.",
      mode: "primary",
      model: "openai/gpt-5.6-sol",
      variant: "low",
      steps: 30,
      permission: { task: { "*": "deny", bulk: "allow", routine: "allow", reviewer: "allow", deep: "allow", "extreme-*": "allow", "flow-*": "allow" } },
      prompt: [
        "Classify each request before acting.",
        "When the user asks to inspect, change, or reset flow-agent models, use flow_models. Explain that the persistent model change takes effect after restarting OpenCode.",
        "Delegate repetitive, low-risk, high-volume transformations requiring little judgment to bulk.",
        "Never use bulk for ambiguous requirements, architecture, security-sensitive work, or difficult debugging.",
        "Delegate bounded routine implementation, exploration, and fast-path work with clear acceptance criteria to routine.",
        "Keep routine planning surface-level and cheap: do not inspect implementation files merely to prepare a packet, enumerate expected file edits, design the detailed solution, or predict the diff. The worker owns repository exploration, detailed planning, and implementation choices.",
        "Routine work packets must stay concise and label Task ID, Objective, Scope, Constraints, Acceptance, Verification, Escalate When, and Return. Reuse the same Task ID for retries and remediation. Scope names the behavior or subsystem, not an exhaustive file list. Treat worker reports without a valid <flow-work-report> as invalid output, but never delegate a separate task solely to repair report formatting.",
        "Architecture, security, authorization, money, destructive data operations, concurrency, and migrations still go to routine first. Give the worker the risk constraints and require it to stop rather than guess.",
        "Use deep only when routine returns a concrete failed or blocked result that economical retries cannot responsibly resolve. Before every deep call, explain the evidence to the user and request one-use approval with flow_approve_escalation.",
        "Before using deep after a worker failure, pass the specific blocker, final diff, and verification evidence so it diagnoses the residue rather than repeats the worker's exploration.",
        "When a loaded skill asks for Agent or general-purpose subagents, translate that intent to the available task subagent whose role best matches the work.",
        "Build a small dependency graph for multi-part work. Dispatch up to three independent read-only or rigorously disjoint units concurrently in one turn; keep dependent or overlapping writes serial. Integrate a completed frontier before dispatching the next one.",
        "For code review, use reviewer from a different model family than the implementation worker and disclose when no independent cross-family reviewer is available. Review is a milestone gate over a substantial self-contained changeset, not a per-commit gate. Cheap lint, type, focused-test, and final integrated-test checks are the routine gates.",
        "Run milestone review when the user explicitly asks, before work leaves the user's hands, when a substantial sampled changeset is selected, or immediately after a self-contained security, authorization, money, secrets, data-integrity, destructive-lifecycle, or migration unit. Do not separately review routine UI, copy, docs, config, or low-risk refactors.",
        "Give reviewer a compact packet labeled Review Milestone, Acceptance, Change Set, Verification, and Risk. Triage every finding: agree and fix now, or disagree and record a one-line reason. Style and issues already covered by lint, types, or tests are not blockers.",
        "Review once by default. Re-review only after non-trivial accepted fixes, include Finding Disposition and Non-trivial Fixes in the second packet, and stop after two total rounds. If review is unavailable, disclose it and perform one careful diff self-review instead of silently skipping the gate.",
        "Treat each delegation as one bounded unit: inspect its result, resolve substantive failures, and stop at the configured task, retry, review, and step budgets.",
        "Continue until the user's acceptance criteria are met, required verification has passed, a configured budget is reached, or a concrete blocker requires user input; do not merely relay a subagent result.",
        "Before using extreme-medium or extreme-high, explain why deep is insufficient and ask the user for approval.",
        "Never use deep merely because a task is long or spans multiple files.",
        "GPT calls must use the OpenAI provider backed by the user's ChatGPT subscription and are reserved for orchestration and escalation.",
        "Command Code is the default provider for bulk, routine, and reviewer work; routine uses DeepSeek V4 Pro.",
      ].join(" "),
    },
    bulk: {
      description: "Handles repetitive, low-risk, token-heavy work with MiMo V2.5.",
      mode: "subagent",
      model: "commandcode/mimo-v2.5",
      steps: 12,
      permission: { task: "deny", todowrite: "deny" },
    },
    routine: {
      description: "Handles bounded routine coding, research, and fast-path work with DeepSeek V4 Pro.",
      mode: "subagent",
      model: "commandcode/deepseek-v4-pro",
      variant: "high",
      steps: 24,
      permission: { task: "deny", todowrite: "deny" },
    },
    reviewer: {
      description: "Independently reviews delegated changes using a compact diff and verification packet.",
      mode: "subagent",
      model: "commandcode/mimo-v2.5-pro",
      steps: 12,
      permission: { edit: "deny", bash: "deny", task: "deny", todowrite: "deny" },
      prompt: [
        "Review only the supplied milestone acceptance criteria, changeset, relevant snippets, and verification evidence.",
        "Prioritize correctness, regressions, security, and meaningful missing tests. Ignore style and checks already covered by lint, types, or tests.",
        "Do not edit files or run shell commands. Return at most five concrete, evidence-backed findings.",
        "End with exactly one <flow-review> JSON object matching the supplied review contract.",
      ].join(" "),
    },
    deep: {
      description: "Escalation-only agent for high-risk design or evidence-backed failures after economical work is exhausted.",
      mode: "subagent",
      model: "openai/gpt-5.6-terra",
      variant: "high",
      steps: 24,
      permission: { task: "deny", todowrite: "deny" },
    },
    "extreme-medium": {
      description: "Exceptional ChatGPT escalation tier; requires user approval.",
      mode: "subagent",
      model: "openai/gpt-5.6-sol",
      variant: "medium",
      steps: 30,
    },
    "extreme-high": {
      description: "Highest ChatGPT escalation tier; requires explicit user approval.",
      mode: "subagent",
      model: "openai/gpt-5.6-sol",
      variant: "high",
      steps: 30,
    },
  },
  agentMetadata: {
    orchestrator: { role: "orchestrator", billingSource: "chatgpt-subscription", risk: "standard" },
    bulk: { role: "bulk-worker", billingSource: "commandcode-credits", risk: "low" },
    routine: { role: "worker", billingSource: "commandcode-credits", risk: "standard" },
    reviewer: { role: "reviewer", billingSource: "commandcode-credits", risk: "low" },
    deep: { role: "escalation", billingSource: "chatgpt-subscription", risk: "high", requiresApproval: true },
    "extreme-medium": {
      role: "escalation",
      billingSource: "chatgpt-subscription",
      risk: "high",
      requiresApproval: true,
    },
    "extreme-high": {
      role: "escalation",
      billingSource: "chatgpt-subscription",
      risk: "high",
      requiresApproval: true,
    },
  },
  routingRules: [
    "Send repetitive, low-risk, token-heavy transformations to bulk.",
    "Send bounded routine implementation, exploration, and fast-path work with clear acceptance criteria to routine.",
    "Send high-risk work to routine first with explicit stop conditions; use deep only for evidence-backed residue after routine fails or blocks.",
    "Use reviewer selectively for missing or failed verification, high-risk changes, and configured samples.",
    "When a workflow explicitly requests code review, prefer reviewer and keep the reviewer in a different model family from the implementation worker where possible.",
  ],
  escalationRules: [
    "Do not escalate merely because a task is long or spans multiple files.",
    "Escalate to deep only after a failed or blocked routine attempt identifies a concrete blocker.",
    "deep, extreme-medium, and extreme-high require an explicit approval token from the plugin.",
    "A worker may retry bounded verification failures before escalating.",
  ],
  verification: {
    enabled: true,
    discoverFromRepository: true,
    maxWorkerAttempts: 2,
    fullSuiteRisk: "high",
  },
  orchestration: {
    maxTasksPerRun: 12,
    maxConcurrentWorkers: 3,
  },
  reviewer: {
    enabled: true,
    agent: "reviewer",
    triggers: ["explicit", "milestone", "high-risk", "sampled"],
    sampleRate: 0.1,
    maxRounds: 2,
    maxFindings: 5,
    maxPacketChars: 12_000,
  },
  limitations: [
    "ChatGPT subscription capacity is not token-metered, so capacity savings remain estimated.",
    "Task-to-child-session linking is correlated when OpenCode does not expose an explicit relationship.",
    "Model review is evidence, not ground truth.",
    "Cross-family review selection is prompt-enforced; user agent overrides can make an independent model unavailable.",
  ],
} satisfies FlowDefinition
