import type { FlowDefinition } from "../types.js"

export const openaiCommandCodeRouter = {
  id: "openai-commandcode-router",
  title: "OpenAI + Command Code Router",
  summary: "Uses a subscription-backed orchestrator and low-cost workers, escalating difficult work back to the baseline model.",
  defaultAgent: "orchestrator",
  baselineAgent: "orchestrator",
  agents: {
    orchestrator: {
      description: "Routes work between ChatGPT and low-cost Command Code models.",
      mode: "primary",
      model: "openai/gpt-5.6-sol",
      variant: "low",
      permission: { task: { "*": "deny", bulk: "allow", routine: "allow", reviewer: "allow", deep: "allow", "extreme-*": "allow", "flow-*": "allow" } },
      prompt: [
        "Classify each request before acting.",
        "Delegate repetitive, low-risk, high-volume transformations requiring little judgment to bulk.",
        "Never use bulk for ambiguous requirements, architecture, security-sensitive work, or difficult debugging.",
        "Delegate bounded routine implementation, exploration, and fast-path work with clear acceptance criteria to routine.",
        "Routine work packets must label Objective, Scope, Constraints, Acceptance, Verification, Escalate When, and Return. Treat worker reports without a valid <flow-work-report> as incomplete.",
        "Use deep only after routine exhausts its bounded repair attempts with concrete verification evidence, or immediately for architecture, ambiguous acceptance criteria, security, authorization, money, destructive data operations, concurrency, or complex migrations.",
        "Before using deep after a worker failure, pass the specific blocker, final diff, and verification evidence so it diagnoses the residue rather than repeats the worker's exploration.",
        "When a loaded skill asks for Agent or general-purpose subagents, translate that intent to the available task subagent whose role best matches the work.",
        "For code review, use a reviewer from a different model family than the agent that implemented the change; prefer reviewer, fall back to another configured different-family subagent, and disclose when no independent cross-family reviewer is available.",
        "Treat each delegation as one unit in a completion loop: inspect its result, resolve failures or missing work, and delegate the next unit when needed.",
        "Continue until the user's acceptance criteria are met, required verification has passed, or a concrete blocker requires user input; do not merely relay a subagent result.",
        "Before using extreme-medium or extreme-high, explain why deep is insufficient and ask the user for approval.",
        "Never use deep merely because a task is long or spans multiple files.",
        "GPT calls must use the OpenAI provider backed by the user's ChatGPT subscription and are reserved for orchestration and escalation.",
        "Command Code is the default provider for bulk, routine, and reviewer work; routine uses DeepSeek V4 Pro.",
      ].join(" "),
    },
    bulk: {
      description: "Handles repetitive, low-risk, token-heavy work with MiMo V2.5.",
      mode: "subagent",
      model: "commandcode/mimo-v2.5",
      permission: { task: "deny", todowrite: "deny" },
    },
    routine: {
      description: "Handles bounded routine coding, research, and fast-path work with DeepSeek V4 Pro.",
      mode: "subagent",
      model: "commandcode/deepseek-v4-pro",
      variant: "high",
      permission: { task: "deny", todowrite: "deny" },
    },
    reviewer: {
      description: "Independently reviews delegated changes using a compact diff and verification packet.",
      mode: "subagent",
      model: "commandcode/mimo-v2.5-pro",
      permission: { edit: "deny", task: "deny", todowrite: "deny" },
      prompt: [
        "Review only the supplied acceptance criteria, diff, relevant snippets, and verification evidence.",
        "Prioritize correctness, regressions, security, and missing tests over style.",
        "Do not edit files. Return concrete findings first and state pass, mixed, or fail.",
        "End with <flow-evaluation> JSON using source cheap-review, verdict good|mixed|bad|unknown, score 1-5, and a brief note.",
      ].join(" "),
    },
    deep: {
      description: "Escalation-only agent for high-risk design or evidence-backed failures after economical work is exhausted.",
      mode: "subagent",
      model: "openai/gpt-5.6-terra",
      variant: "high",
      permission: { task: "deny", todowrite: "deny" },
    },
    "extreme-medium": {
      description: "Exceptional ChatGPT escalation tier; requires user approval.",
      mode: "subagent",
      model: "openai/gpt-5.6-sol",
      variant: "medium",
    },
    "extreme-high": {
      description: "Highest ChatGPT escalation tier; requires explicit user approval.",
      mode: "subagent",
      model: "openai/gpt-5.6-sol",
      variant: "high",
    },
  },
  agentMetadata: {
    orchestrator: { role: "orchestrator", billingSource: "chatgpt-subscription", risk: "standard" },
    bulk: { role: "bulk-worker", billingSource: "commandcode-credits", risk: "low" },
    routine: { role: "worker", billingSource: "commandcode-credits", risk: "standard" },
    reviewer: { role: "reviewer", billingSource: "commandcode-credits", risk: "low" },
    deep: { role: "escalation", billingSource: "chatgpt-subscription", risk: "high" },
    "extreme-medium": {
      role: "escalation",
      billingSource: "chatgpt-subscription",
      risk: "high",
      requiresApproval: true,
    },
    "extreme-high": {
      role: "escalation",
      billingSource: "chatgpt-subscription",
      risk: "high",
      requiresApproval: true,
    },
  },
  routingRules: [
    "Send repetitive, low-risk, token-heavy transformations to bulk.",
    "Send bounded routine implementation, exploration, and fast-path work with clear acceptance criteria to routine.",
    "Use deep only for high-risk work or evidence-backed residue after routine exhausts its bounded retries; provide the blocker, diff, and verification evidence.",
    "Use reviewer selectively for missing or failed verification, high-risk changes, and configured samples.",
    "When a workflow explicitly requests code review, prefer reviewer and keep the reviewer in a different model family from the implementation worker where possible.",
  ],
  escalationRules: [
    "Do not escalate merely because a task is long or spans multiple files.",
    "Escalate to deep after routine exhausts its bounded retries only when deterministic verification, requirements, or repository evidence identify a concrete blocker.",
    "extreme-medium and extreme-high require an explicit approval token from the plugin.",
    "A worker may retry bounded verification failures before escalating.",
  ],
  verification: {
    enabled: true,
    discoverFromRepository: true,
    maxWorkerAttempts: 2,
    fullSuiteRisk: "high",
  },
  reviewer: {
    enabled: true,
    agent: "reviewer",
    triggers: ["failed-verification", "missing-verification", "high-risk", "sampled"],
    sampleRate: 0.1,
  },
  limitations: [
    "ChatGPT subscription capacity is not token-metered, so capacity savings remain estimated.",
    "Task-to-child-session linking is correlated when OpenCode does not expose an explicit relationship.",
    "Model review is evidence, not ground truth.",
    "Cross-family review selection is prompt-enforced; user agent overrides can make an independent model unavailable.",
  ],
} satisfies FlowDefinition
