import type { FlowReport, GlobalReport } from "./types.js"

function safeJson(value: unknown): string {
  return JSON.stringify(value).replaceAll("<", "\\u003c")
}

export function renderDashboard(global: GlobalReport, reports: FlowReport[]): string {
  const data = safeJson({ global, reports: reports.slice(-100).reverse() })
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'"><title>Agent Flow Observatory</title>
<style>
:root{color-scheme:dark;--bg:#0b0d0f;--panel:#14181c;--line:#29343d;--text:#edf3f7;--muted:#9eabb5;--cyan:#52d3c8;--amber:#efb95b;--red:#ef7373}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 88% -20%,#183d44,transparent 38%),var(--bg);color:var(--text);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}main{max-width:1440px;margin:auto;padding:32px 24px 80px}header{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:24px}h1{margin:0;font:700 clamp(28px,4vw,48px)/1 ui-sans-serif,system-ui;letter-spacing:-.04em}h2{margin:0 0 14px;font-size:13px;text-transform:uppercase;letter-spacing:.13em;color:var(--muted)}.eyebrow,.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:16px}.card,.panel{border:1px solid var(--line);background:color-mix(in srgb,var(--panel) 94%,transparent);border-radius:12px;box-shadow:0 16px 60px #0004}.card{padding:17px}.card strong{display:block;margin-top:8px;font:700 25px/1 ui-sans-serif,system-ui}.accent{color:var(--cyan)}.layout{display:grid;grid-template-columns:1.1fr .9fr;gap:16px;margin-bottom:16px}.panel{padding:20px;overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:10px 8px;text-align:left;border-bottom:1px solid var(--line);white-space:nowrap}th{color:var(--muted);font-weight:500}.num{text-align:right}.run{cursor:pointer}.run:hover,.run.selected{background:#203136}.pill{display:inline-block;padding:3px 8px;border-radius:99px;background:#203136;color:var(--cyan);font-size:12px}.bar{height:8px;background:#252c32;border-radius:99px;overflow:hidden;margin-top:8px}.bar span{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),#72a9ff)}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px}.empty,.note{padding:18px 0;color:var(--muted)}.warning{color:var(--amber)}code{color:var(--cyan)}@media(max-width:1000px){.grid{grid-template-columns:repeat(3,1fr)}.layout,.split{grid-template-columns:1fr}}@media(max-width:600px){main{padding:20px 12px}.grid{grid-template-columns:repeat(2,1fr)}header{align-items:start;flex-direction:column}.panel{padding:14px}}
</style></head><body><main>
<header><div><div class="eyebrow">OPENCODE / FLOW TELEMETRY</div><h1>Agent Flow Observatory</h1></div><div class="muted" id="updated"></div></header>
<section class="grid" id="cards"></section>
<section class="layout"><div class="panel"><h2>Runs — select one for details</h2><div id="runs"></div></div><div class="panel"><h2>Developer evaluation mode</h2><div id="developer"></div><h2 style="margin-top:24px">Quota and budget</h2><div id="quotas"></div></div></section>
<section class="split"><div class="panel"><h2>Model costs — selected run</h2><div id="models"></div></div><div class="panel"><h2>Agent costs — selected run</h2><div id="agents"></div></div></section>
</main><script>
const DATA=${data},g=DATA.global,reports=DATA.reports;let selected=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>'$'+Number(n||0).toFixed(4);const duration=ms=>ms==null?'Unavailable':ms<1000?Math.round(ms)+'ms':ms<60000?(ms/1000).toFixed(1)+'s':ms<3600000?Math.floor(ms/60000)+'m '+Math.round(ms%60000/1000)+'s':Math.floor(ms/3600000)+'h';
const api=(cost,unpriced)=>Number(unpriced||0)>0?(Number(cost||0)>0?money(cost)+' + ':'')+unpriced+' unpriced':money(cost);const apiTotal=t=>api(t?.apiEquivalentCostUsd,t?.apiEquivalentUnpricedCalls);
document.querySelector('#updated').textContent='Updated '+new Date(g.generatedAt).toLocaleString();
document.querySelector('#cards').innerHTML=[['Runs',g.runs],['Metered cost',money(g.totals.costUsd)],['API-equivalent',apiTotal(g.totals)],['Subagent calls',g.totals.subagentsSpawned],['Average time',duration(g.averageDurationMs)]].map(([k,v],i=>'<div class="card"><small>'+k+'</small><strong class="'+(i===2?'accent':'')+'">'+v+'</strong></div>')).join('');
function renderRuns(){document.querySelector('#runs').innerHTML=reports.length?'<table><thead><tr><th>Run</th><th>Flow</th><th class="num">Time</th><th class="num">Metered</th><th class="num">API-eq.</th></tr></thead><tbody>'+reports.map((r,i)=>'<tr class="run '+(i===selected?'selected':'')+'" data-run="'+i+'"><td><span class="pill">'+esc(String(r.runID||'session').slice(-10))+'</span></td><td>'+esc(r.flowTitle)+'</td><td class="num">'+duration(r.durationMs)+'</td><td class="num">'+money(r.totals.costUsd)+'</td><td class="num">'+apiTotal(r.totals)+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">No completed runs yet.</div>';document.querySelectorAll('[data-run]').forEach(el=>el.onclick=()=>{selected=Number(el.dataset.run);renderRuns();renderDetails()})}
function renderDetails(){const r=reports[selected];if(!r){document.querySelector('#models').innerHTML=document.querySelector('#agents').innerHTML='<div class="empty">No run selected.</div>';return}const modelRows=r.byModel||[],agentRows=r.byAgent||[];document.querySelector('#models').innerHTML=modelRows.length?'<table><thead><tr><th>Model</th><th class="num">Calls</th><th class="num">Tokens</th><th class="num">Metered</th><th class="num">API-eq.</th></tr></thead><tbody>'+modelRows.map(m=>'<tr><td>'+esc(m.providerID+'/'+m.modelID)+'</td><td class="num">'+m.calls+'</td><td class="num">'+Number(m.workloadUnits||0).toLocaleString()+'</td><td class="num">'+money(m.costUsd)+'</td><td class="num">'+api(m.apiEquivalentCostUsd,m.apiEquivalentUnpricedCalls)+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">No model calls recorded.</div>';document.querySelector('#agents').innerHTML=agentRows.length?'<table><thead><tr><th>Agent / role</th><th>Model</th><th class="num">Calls</th><th class="num">Metered</th><th class="num">API-eq.</th></tr></thead><tbody>'+agentRows.map(a=>'<tr><td>'+esc(a.agent)+'<br><span class="muted">'+esc(a.role)+'</span></td><td>'+esc(a.modelID||'unknown')+'</td><td class="num">'+a.calls+'</td><td class="num">'+money(a.costUsd)+'</td><td class="num">'+api(a.apiEquivalentCostUsd,a.apiEquivalentUnpricedCalls)+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">No agent activity recorded.</div>';const d=r.developerMode;document.querySelector('#developer').innerHTML=d?'<div><strong class="'+(d.enabled?'accent':'warning')+'">'+(d.enabled?'Enabled':'Disabled')+'</strong><p class="muted">Audit '+d.auditReview+' · Shadow plan '+d.shadowPlanning+' · Shadow implementation '+d.shadowImplementation+' · Sample '+Math.round(d.sampleRate*100)+'%</p><p class="note">Change it with <code>flow_developer_mode</code>; no JSON edit or restart is required.</p></div>':'<div class="empty">No developer-mode snapshot was recorded for this older run.</div>'}
const qs=g.latestQuotas||[];document.querySelector('#quotas').innerHTML=qs.length?qs.map(q=>{const used=q.primary?.usedPercent??(q.allowanceUsd?100*(q.spentUsd||0)/q.allowanceUsd:0);return '<div><div style="display:flex;justify-content:space-between"><span>'+esc(q.source)+'</span><span>'+Number(used).toFixed(1)+'%</span></div><div class="bar"><span style="width:'+Math.min(100,used)+'%"></span></div></div>'}).join('<br>'):'<div class="empty">No quota source available.</div>';renderRuns();renderDetails();
</script></body></html>`
}
