import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { flows } from "../src/flows/index.js"
import type { FlowDefinition } from "../src/types.js"

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const outputDirectory = join(root, "docs", "flows")
const check = process.argv.includes("--check")

function nodeID(value: string): string {
  return value.replace(/[^a-zA-Z0-9]/g, "_")
}

function render(flow: FlowDefinition): string {
  const baseline = flow.agents[flow.baselineAgent]
  const simpleEdges = Object.entries(flow.agentMetadata)
    .filter(([name]) => name !== flow.defaultAgent)
    .map(([name, metadata]) => `    ${nodeID(flow.defaultAgent)} -->|${metadata.role}| ${nodeID(name)}[${name}]\n    ${nodeID(name)} --> ${nodeID(flow.defaultAgent)}`)
    .join("\n")
  const agentRows = Object.entries(flow.agents).map(([name, agent]) => {
    const metadata = flow.agentMetadata[name]
    return `| \`${name}\` | ${metadata?.role ?? "unknown"} | \`${agent.model}\` | ${agent.variant ?? "default"} | ${metadata?.billingSource ?? "unknown"} | ${metadata?.requiresApproval ? "Yes" : "No"} |`
  }).join("\n")
  const detailedSteps = Object.entries(flow.agentMetadata)
    .filter(([name]) => name !== flow.defaultAgent)
    .map(([name, metadata]) => `    O->>+${nodeID(name)}: ${metadata.role} task\n    ${nodeID(name)}-->>-O: result and evidence`)
    .join("\n")

  return `<!-- Generated by scripts/generate-docs.ts. Do not edit directly. -->
# ${flow.title}

${flow.summary}

## Simple View

\`\`\`mermaid
flowchart LR
    U[User] --> ${nodeID(flow.defaultAgent)}[${flow.defaultAgent}]
${simpleEdges}
    ${nodeID(flow.defaultAgent)} --> V[Verification]
    V --> U
\`\`\`

The baseline is \`${flow.baselineAgent}\` using \`${baseline?.model ?? "unknown"}\`. Workers return their result to the orchestrator; the orchestrator remains responsible for verification and the final response.

## Detailed View

\`\`\`mermaid
sequenceDiagram
    participant U as User
    participant O as ${flow.defaultAgent}
${Object.keys(flow.agentMetadata).filter((name) => name !== flow.defaultAgent).map((name) => `    participant ${nodeID(name)} as ${name}`).join("\n")}
    U->>O: Request
${detailedSteps}
    O->>O: Select targeted verification
    O-->>U: Verified result and run summary
\`\`\`

### Agents

| Agent | Role | Model | Effort | Billing source | Approval required |
|---|---|---|---|---|---|
${agentRows}

### Routing

${flow.routingRules.map((rule) => `- ${rule}`).join("\n")}

### Escalation

${flow.escalationRules.map((rule) => `- ${rule}`).join("\n")}

### Verification

- Repository discovery: ${flow.verification.discoverFromRepository ? "enabled" : "disabled"}
- Maximum worker attempts: ${flow.verification.maxWorkerAttempts}
- Full-suite threshold: ${flow.verification.fullSuiteRisk} risk
- The plugin records observed checks; passing checks are evidence, not proof of correctness.

### Reviewer

${flow.reviewer ? `The \`${flow.reviewer.agent}\` agent is ${flow.reviewer.enabled ? "enabled" : "disabled"} by default. Triggers: ${flow.reviewer.triggers.join(", ")}. Sample rate: ${Math.round(flow.reviewer.sampleRate * 100)}%.` : "No reviewer is configured."}

### Telemetry

Every root user turn becomes a run. Reports include actual model/provider usage, billing source, subagent count, tasks, verification evidence, evaluator cost, explicit feedback, and quota snapshots. Task-to-child linkage is marked as correlated unless OpenCode exposes an explicit identifier.

### Limitations

${flow.limitations.map((limitation) => `- ${limitation}`).join("\n")}
`
}

await mkdir(outputDirectory, { recursive: true })
let failed = false
for (const [name, flow] of Object.entries(flows)) {
  const path = join(outputDirectory, `${name}.md`)
  const contents = render(flow)
  if (check) {
    const current = await readFile(path, "utf8").catch(() => "")
    if (current !== contents) {
      console.error(`Generated flow documentation is stale: ${path}`)
      failed = true
    }
  } else {
    await writeFile(path, contents, "utf8")
  }
}
if (failed) process.exit(1)
